services:
  django:
    image: gol:backend
    ports:
      - 8000:8000
    volumes:
      - './gol/:/app/'

  frontend:
    image: gol:frontend
    tty: true
    ports:
      - '${DJANGO_VITE_DEV_SERVER_PORT}:${DJANGO_VITE_DEV_SERVER_PORT}'
    volumes:
      - './gol:/app/'
    env_file:
      - "./.env"
